services:
  postgres:
    image: postgres:15
    container_name: gradebook-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: gradebook
      POSTGRES_USER: gbuser
      POSTGRES_PASSWORD: gbpass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gradebook-net

  redis:
    image: redis:7-alpine
    container_name: gradebook-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - gradebook-net

  gradebook-app:
    build: .
    image: gradebook-app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - gradebook-net
    restart: always


volumes:
  postgres_data:
  redis_data:

networks:
  gradebook-net: